name: Release Super POM to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure Git
        run: |
          git config user.name "liquibot"
          git config user.email "liquibot@liquibase.org"

      - name: Build release artifacts
        id: build-release-artifacts
        run: |
          mvn -B release:clean release:prepare -Dusername=liquibot -Dpassword=$GITHUB_TOKEN -Darguments="-Dmaven.javadoc.skip=true -Dmaven.test.skipTests=true -Dmaven.test.skip=true -Dmaven.deploy.skip=true" -DpushChanges=false
          git reset HEAD~ --hard

      - name: Get Artifact ID
        id: get-artifact-id
        run: echo "artifact_id=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

      - name: Download Release Artifacts
        uses: robinraju/release-downloader@v1.6
        with:
          tag: "${{ github.event.release.tag_name }}"
          filename: "${{ env.artifact_id }}-*"
          out-file-path: "."

      - name: Publish to GitHub Packages
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mvn deploy:deploy-file -Dusername=liquibot -Dpassword=$GITHUB_TOKEN -DpomFile=${{ env.artifact_id }}-${version}.pom -Dfile=${{ env.artifact_id }}-${version}.pom -DrepositoryId=github -Durl=https://maven.pkg.github.com/liquibase/liquibase-super-pom       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  maven-release:
    needs: release
    uses: liquibase/build-logic/.github/workflows/extension-release-prepare.yml@v0.4.1
    secrets: inherit