name: Release Parent POM to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
  
jobs:
  release:
    uses: liquibase/build-logic/.github/workflows/extension-release-published.yml@v0.4.2
    secrets: inherit

  maven-release:
    needs: release
    uses: liquibase/build-logic/.github/workflows/extension-release-prepare.yml@v0.4.2
    secrets: inherit